version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - ./backend/.env.docker
    networks:
      - mi-red

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mi-red

volumes:
  postgres_data:

networks:
  mi-red:
