services:
  app:
    build: ./backend .
    container_name: app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mi-red

  jenkins:
    build: ./jenkins
    container_name: jenkins
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mi-red

volumes:
  postgres_data:
  jenkins_data:

networks:
  mi-red:
